### ISSUE TITLE
equipment purchasing: projector

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#28]
We could buy an additional projector, as ours is now 10+ years old. I think we have something like this [Epson](https://www.amazon.com/Epson-EX3280-Projector-Brightness-Speaker/dp/B08P58JXJ9) one (is ours Epson)? 

I would be open to another one of similar style though.

We could also get a mini projector (in addition or instead), but I am struggling to figure out how much we have to spend for one that works for presentations. Here's some reviews:

- [techradar](https://www.techradar.com/news/best-portable-projectors)
- [best pico projectors](https://www.seenebula.com/blogs/buying-guides/best-pico-projector)
- [pc mag](https://www.pcmag.com/picks/the-best-portable-projectors)

Any thoughts?

**Comment by christophe-rd** [comment]
I don't have any strong thoughts as I have little experience with projectors. However, these products both seem great:
### Portable
#### Epson PowerLite 1795F Projector
White brightness: 3,200 Lumens
Projector dimensions: 5 cm x 29 cm x 21 cm
Resolution:  1920x1080 
Price: [1385](https://www.amazon.ca/Epson-PowerLite-adjustments-powerhouse-presentations/dp/B01N0YGEQT?th=1)
Recommended by a random dude on Reddit and [here](https://www.projectorcentral.com/Epson-PowerLite_1795F.htm): 

#### Dangbei Atom Projector
White brightness: 1200 Lumens (quite low)
Projector dimensions: 5 cm x 20 cm x 20 cm
Resolution:  1920x1080 
Price: [1000$ ](https://www.amazon.ca/Dangbei-Projector-Assistant-Chromecast-Correction/dp/B0CLP5WMXC)
It would be the[best portable projector ](https://www.projectorcentral.com/Dangbei-Atom.htm)

#### NEBULA Mars 3 Air GTV Projector 
White brightness: 400 lumens (very low)
Product Dimensions :  ‎17.78 x 12.19 x 13.28 cm
Resolution:  ‎1920 x 1080 
Price: [870$ - 250$ coupon](https://www.amazon.ca/dp/B0CHW168LV?tag=cnet-can-geniuslink-20&ascsubtag=4e1d8e50d2c3459e93fcf5aa74570d92|13fb6ad8-9917-4fa7-b971-53ac7903e565|dtp|cn&geniuslink=true)

### Non-Portable (well, it's not their purpose)
#### BenQ HT2060
White brightness: 2200 lumens
Product Dimensions :  36.58 x 24.38 x 13.21 cm
Resolution:  1920x1080 1
Price: [1100$](https://www.amazon.ca/dp/B0BWGXHVRV?ascsubtag=F0401HZT24K6GC460R12GMWKR55PG&linkCode=gs2&tag=thewire0f-20&th=1)

#### BenQ Ace AH700ST
White brightness: 4000 lumens
Product Dimensions :  30 x 11 x 23 cm
Resolution:  1920x1080 
Price: [2600$](https://www.avshop.ca/video/projectors/benq-ah700st-4000-lumen-short-throw-1080p-laser-golf-simulator-projector?srsltid=AfmBOorGbxrLyu-T6bOx2vM4aRBrLHquh1qsAtZGIC3Nu8Qzt9TkXJOv)
This would be the best projector for classrooms.

My opinion: I would get a good small (but not pocket) size projector instead of two, but I have no idea of the lab's needs. The Epson I showed above seems to be be great!

**Comment by wangxm-forest** [comment]
I had a NEBULA portable projector before, and I really liked it. The only issue I encountered was that it doesn’t perform well in rooms that aren’t dark enough, but I suppose that’s the compromise for its compact size...

**Comment by lizzieinvancouver** [comment]
@wangxm-forest @christophe-rd Thanks for your help! I suggest we get the Epson PowerLite 1795F Projector in the end. @wangxm-forest if you get the corporate card working, can you order this also?

**Comment by christophe-rd** [comment]
Purchased! Closing issue
