### ISSUE TITLE
equipment purchasing: computer

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#29]
@afong3 Did we ever buy a decent PC desktop (or laptop) for the lab?

I feel like we should get 1-2 more computers for sharing in the lab before our budget runs out ....

**Comment by christophe-rd** [comment]
@lizzieinvancouver Yes Adam bought a Lenovo Legion.

**Comment by afong3** [comment]
@lizzieinvancouver The Lenovo Legion seems to work for everything that I've used it for including 3D modelling with medium size assemblies. It also has a nice graphics card which should be able to run some deep-learning models if wanted. 

I'm not sure what the computing priorities are moving forward for the lab but it never hurts to have powerful computers around if the money wouldn't be spent elsewhere.

**Comment by lizzieinvancouver** [comment]
@christophe-rd Thanks! I will take a look. I think we likely want a cheaper Mac desktop and laptop and maybe one more nice desktop. I worry we will not use the full capacity of a nice laptop and be sad if it gets stolen, but I will take advice/opinions from you @wangxm-forest @afong3 and @kengi-neer.

**Comment by lizzieinvancouver** [comment]
@christophe-rd @afong3 @wangxm-forest I have made a note to order what we can afford once I am back and have finalized some budgeting. If you have any thoughts/ideas/requests, feel free to share whenever.

**Comment by christophe-rd** [comment]
> @christophe-rd @afong3 @wangxm-forest I have made a note to order what we can afford once I am back and have finalized some budgeting. If you have any thoughts/ideas/requests, feel free to share whenever.

@lizzieinvancouver perfect! Once we know what we can afford, I could look at some options.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver
We have an old Mac desktop and an old Apple monitor in the lab that I don't think anyone is currently using. If we decide to purchase anything from Apple, maybe we could consider trading them in?

**Comment by lizzieinvancouver** [comment]
@wangxm-forest You can email the serial numbers and I can check but in my experience our equipment is always too old to get any trade-in value.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest @christophe-rd @afong3 I am thinking to buy for the lab:

1. A plain macbook air 
2. an iMac
3. Some decent windows laptop for 1400 or under

But this is your chance to make a case for something else! Also, if anyone has suggestions for a windows laptop, let me know!

**Comment by wangxm-forest** [comment]
What are we expecting to do with these laptops?

As a personal fan of ThinkPads, I'd like to recommend a few options. If we're looking for powerful performance, I suggest considering the [ThinkPad P series](https://www.lenovo.com/ca/en/p/laptops/thinkpad/thinkpadp/thinkpad-p16-gen-2-16-inch-intel/21fa0028us). These are mobile workstations, great for demanding tasks. However, the downside is that they are really heavy and not ideal for frequent travel.

If portability is required but we still need solid performance, I recommend the [ThinkPad T series](https://www.lenovo.com/ca/en/p/laptops/thinkpad/thinkpadt/thinkpad-t16-gen-2-16-inch-amd/len101t0076). These laptops are lighter but still capable of handling most tasks. I've personally used two T series laptops and loved them.

For something even more ultraportable (perfect for fieldwork or travel), I'd recommend the [ThinkPad X series](https://www.lenovo.com/ca/en/p/laptops/thinkpad/thinkpadx1/thinkpad-x1-carbon-gen-11-14-inch-intel/len101t0049?orgRef=https%253A%252F%252Fwww.google.com%252F&sortBy=priceUp&cid=ca:sem%7cse%7cgoogle%7csubbrand_pc_thinkpad%7c%7cthinkpad%20x%20series%7cb%7c84051218%7c153141724046%7caud-515629264997:kwd-54365606%7csearch%7cbrand%7cconsumer&gad_source=1&gclid=CjwKCAiA9bq6BhAKEiwAH6bqoEu6Wm45BOEuyiEYh3S8pR7eMNuNy7bgejEzpLPTOZLcYGvUfOEfIhoCOqQQAvD_BwE). These are very light and ideal for carrying around, but I don't think it will be able to handle complex models or tasks like that.

I could be super biased though, since I personally never had a macbook air before.

**Comment by christophe-rd** [comment]
> @wangxm-forest @christophe-rd @afong3 I am thinking to buy for the lab:
> 
>     1. A plain macbook air
> 
>     2. an iMac
> 
>     3. Some decent windows laptop for 1400 or under
> 
> 
> But this is your chance to make a case for something else! Also, if anyone has suggestions for a windows laptop, let me know!

I have a question regarding the purchase of lower-end computers. Assuming most of the students joining the lab will have their own computer, why would they use the lab's? Is that something you would prefer @lizzieinvancouver?

This is just my personal experience, but I used the Legion for the last few weeks, which has a much more powerful graphic card than my computer. However, I only use it for demanding tasks as working on two devices is not something I find efficient. 
Another concern I have is that tech advances so quickly that I am afraid buying lower-end computer will make them obsolete faster than if we bought more powerful ones. I might be wrong though.

My opinion: I would purchase less, but more powerful PCs (not Macs) because I feel like some software we are likely to use might only be available on PCs. E.g. Coorecorder. 
That being said, iMacs are cool and very nice to work on!

**Comment by lizzieinvancouver** [comment]
@wangxm-forest @christophe-rd Thanks for all the feedback! You're both making me think perhaps we do not need more laptops as I do not have a clear plan for them and that means maybe the lab does not have a need for them.... People have used them in the past when they needed one, but grad students can likely borrow from FRST or BRC if needed. It's nice to have one to offer UGs but we cannot be in a position where we ask students to use lab laptops (we cannot provide enough of them and they likely would go missing). 

@christophe-rd I agree that tech changes fast but that seems more a reason NOT to invest in high-end laptops ... especially when we have one and have midge ... or am I missing some logic here? 

I like Macs because they have a Unix interface and are what I use. The lab has generally has fewer PCs as most of us do not use PCs ... if we want, we could get another Unix machine, but I am not sure I understand why to get more PCs given to date most of the lab uses Macs (though there is NO rule in the lab about what type of computer to use if it works for you and the lab policies on using GitHub etc.). 

We could get an iMac and a nice-ish PC or Unix desktop? I am spit-balling here.

@afong3 Last day to weigh in!

@wangxm-forest @christophe-rd Any more thoughts based on this? And thank you again for the feedback and thoughts!

**Comment by christophe-rd** [comment]
@lizzieinvancouver I think that's a good plan!

**Comment by lizzieinvancouver** [comment]
Thanks for all your help! I ordered two desktops. An iMac and a Titan. Here's some notes on that....

Titan recommendations:
- Get enough power; first person said at least 10K watt, next guy said 12.5K watt
- Get one good video card versus 2 cheap ones
- Which NVIDIA card? 
	- First guy said: NVIDIA a5000 5000eta (or anything in between) (4070 4080 quadro) -- don't get g-force
	- Second guy recommended: A5000 Quadro, maybe Geforce RTX Super 4080 and Ada 4000 -- better than Geforce $1400. After I told him we'd be new to GPU, he suggested we try 4070 SUPER... start there and replace later if it works well (and get 12.5K power)

Work station model: A-870 -- newest stuff on these

<img width="869" alt="Screenshot 2024-12-15 at 9 11 57 AM" src="https://github.com/user-attachments/assets/58fd0712-e53c-4dbd-a5f7-bc7fb5051e25" />
